BEGIN;

CREATE TABLE IF NOT EXISTS public."LivePulse_events" (
    id TEXT PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    presentation_token TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'DRAFT'
        CHECK (status IN ('DRAFT', 'LOBBY', 'RUNNING', 'ENDED')),
    display_mode TEXT NOT NULL DEFAULT 'LOBBY'
        CHECK (
            display_mode IN (
                'LOBBY',
                'WAITING',
                'QUESTION',
                'QUESTION_CLOSED',
                'RESULT',
                'ENDED'
            )
        ),
    current_question_id TEXT,
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public."LivePulse_questions" (
    id TEXT PRIMARY KEY,
    event_id TEXT NOT NULL
        REFERENCES public."LivePulse_events"(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('SINGLE', 'RATING')),
    status TEXT NOT NULL DEFAULT 'READY'
        CHECK (status IN ('DRAFT', 'READY', 'OPEN', 'CLOSED', 'REVEALED')),
    position INTEGER NOT NULL CHECK (position > 0),
    chart_type TEXT NOT NULL DEFAULT 'BAR'
        CHECK (chart_type IN ('BAR', 'PIE')),
    min_label TEXT NOT NULL DEFAULT '',
    max_label TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT "LivePulse_questions_event_position_unique"
        UNIQUE (event_id, position)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS public."LivePulse_options" (
    id TEXT PRIMARY KEY,
    question_id TEXT NOT NULL
        REFERENCES public."LivePulse_questions"(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    position INTEGER NOT NULL CHECK (position > 0),
    value INTEGER CHECK (value IS NULL OR value BETWEEN 1 AND 5),
    UNIQUE (question_id, position)
);

CREATE TABLE IF NOT EXISTS public."LivePulse_participant_sessions" (
    id TEXT PRIMARY KEY,
    event_id TEXT NOT NULL
        REFERENCES public."LivePulse_events"(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS public."LivePulse_responses" (
    id TEXT PRIMARY KEY,
    question_id TEXT NOT NULL
        REFERENCES public."LivePulse_questions"(id) ON DELETE CASCADE,
    participant_session_id TEXT NOT NULL
        REFERENCES public."LivePulse_participant_sessions"(id) ON DELETE CASCADE,
    option_id TEXT NOT NULL
        REFERENCES public."LivePulse_options"(id) ON DELETE RESTRICT,
    submitted_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (question_id, participant_session_id)
);

CREATE TABLE IF NOT EXISTS public."LivePulse_event_logs" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL
        REFERENCES public."LivePulse_events"(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conname = 'LivePulse_events_current_question_fk'
           AND conrelid = 'public."LivePulse_events"'::REGCLASS
    ) THEN
        ALTER TABLE public."LivePulse_events"
            ADD CONSTRAINT "LivePulse_events_current_question_fk"
            FOREIGN KEY (current_question_id)
            REFERENCES public."LivePulse_questions"(id)
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS "LivePulse_idx_questions_event_position"
    ON public."LivePulse_questions"(event_id, position);

CREATE INDEX IF NOT EXISTS "LivePulse_idx_participants_event"
    ON public."LivePulse_participant_sessions"(event_id);

CREATE INDEX IF NOT EXISTS "LivePulse_idx_responses_question"
    ON public."LivePulse_responses"(question_id);

CREATE INDEX IF NOT EXISTS "LivePulse_idx_event_logs_event_created"
    ON public."LivePulse_event_logs"(event_id, created_at);

ALTER TABLE public."LivePulse_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."LivePulse_questions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."LivePulse_options" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."LivePulse_participant_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."LivePulse_responses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."LivePulse_event_logs" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."LivePulse_events" FROM anon, authenticated;
REVOKE ALL ON TABLE public."LivePulse_questions" FROM anon, authenticated;
REVOKE ALL ON TABLE public."LivePulse_options" FROM anon, authenticated;
REVOKE ALL ON TABLE public."LivePulse_participant_sessions" FROM anon, authenticated;
REVOKE ALL ON TABLE public."LivePulse_responses" FROM anon, authenticated;
REVOKE ALL ON TABLE public."LivePulse_event_logs" FROM anon, authenticated;

COMMIT;
